### ISSUE TITLE
Suggesting the .gitignore to remove the non required files in the Repo

### ISSUE THREAD

**Issue by AzhamProdLive** [Ring-Dev/crimsonlove#1]
As stated in the title, y'all should put a .gitignore so the commits removes the non necessary files that users don't need at all, for example the folder .vscode or the cache folder, it will make it more appealing and better to find stuff for people, just a suggestion. 

As I can't create pull requests, I'm making an issue instead lmao

**Comment by AzhamProdLive** [comment]
If you need a .gitignore example I can give you one if needed ofc

**Comment by jaydeslibrary** [comment]
Thank you, _github didn't give me a notification for this..._ I'll get that sorted out for next release, since chapter 3 is already packed.

**Comment by AzhamProdLive** [comment]
No problem, when I'll log back on Desktop, I'll mark this issue as resolved
